# Generated by Django 5.1 on 2024-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginIPS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default=' '),
            preserve_default=False,
        ),
    ]
